Postgres add support for partial index
fluentmigrator/fluentmigrator pull request #1386
Opened 2020-12-05 16:07 UTC by lillo42

Add support for partial index https://github.com/fluentmigrator/fluentmigrator/issues/1367

2020-12-15 14:33 UTC, jzabroski requested changes

2020-12-18 15:32 UTC, jzabroski approved these changes

2020-12-18 15:33 UTC, jzabroski commented
@lillo42 It looks like there are conflicts.  Can you resolve them with master and I will merge?

2020-12-18 16:28 UTC, lillo42 commented
@jzabroski conflicts fixes :)

2020-12-18 18:32 UTC, merged